service: geraldtechrisk
provider:
  profile: allyn-geraldtech
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'} 
  memorySize: 128
  timeout: 30
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: service.geraldtech.nodejs.lambdas.${self:provider.stage}
  environment:
    STAGE:  ${opt:stage,'dev'}
    REGION: ${opt:region, self:provider.region}
    ACCOUNTID: ${file(config.${self:provider.stage}.json):AWS_ACT_ID}  
package:
  individually: false
  excludeDevDependencies: false
functions:
   addMerchant:
    handler: handler.risk
    events:
      - http:
          path: /user/risk
          method: post
          authorizer: aws_iam
          cors: true     
custom:
   prune:
     automatic: true
     number: 5   
plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies